all:
	./gen_dict.pl dict dict_10w 100000
	./gen_dict.pl dict dict_50w 500000
	./gen_dict.pl dict dict_100w 1000000
	./gen_dict.pl dict dict_200w 2000000
	./gen_dict.pl dict dict_300w 3000000
	./gen_dict.pl dict dict_400w 4000000
	./gen_dict.pl dict dict_500w 5000000

clean:
	-rm -rf dict_*
